'use client'
import Nav from '@/components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/UI/Footer'
import { Provider } from 'react-redux'
import { store } from './store/store'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
<html lang="en">
      <Provider store={store}>
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />  
        </body>
      </Provider>
      
    </html>
  
    
  )
}
