'use client'
import Nav from '@/components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/UI/Footer'
import { Provider, useSelector } from 'react-redux'
import { RootState, store } from './store/store'
import { useEffect } from 'react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en">

      <Provider store={store}>
        <Body>
          <Nav />
          {children}
          <Footer />
        </Body>
      </Provider>

    </html>


  )
}

function Body({ children }: any) {

  let theme = useSelector((state: RootState) => state.theme.theme)
  useEffect(()=>{},[theme])
  return <body className={`${inter.className} bg-${theme}-200`}>{children}</body>
}
